[tool.briefcase]
project_name = "delivery"
bundle = "com.delivery.hronrad"
version = "0.0.1"
url = "https://hronrad.delivery.com/delivery"
license = "BSD license"
author = 'Hronrad'
author_email = "2452167810@qq.com"

[tool.briefcase.app.delivery]
formal_name = "delivery"
description = "My first application"
icon = "src/delivery/resources/delivery"
sources = ['src/delivery']
requires = [
]


[tool.briefcase.app.delivery.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.delivery.linux]
requires = [
    'toga-gtk>=0.3.0.dev32',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.delivery.windows]
requires = [
    'toga-winforms>=0.3.0.dev32',
]

# Mobile deployments
[tool.briefcase.app.delivery.iOS]
requires = [
    'toga-iOS>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.delivery.android]
requires = [
    'toga-android>=0.3.0.dev32'
]
